name: hackingtoolsguienv
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - openssl=1.1.1b
  - pip=19.0.3=py37_0
  - python=3.7.2
  - setuptools=40.8.0=py37_0
  - sqlite=3.27.2
  - wheel=0.33.1=py37_0
  - pip:
    - altgraph==0.16.1
    - astroid==2.2.5
    - bleach==3.1.0
    - cffi==1.12.1
    - chardet==3.0.4
    - click==7.0
    - click-plugins==1.0.4
    - colorama==0.4.1
    - dis3==0.1.3
    - django
    - docutils==0.14
    - entrypoints==0.3
    - flask==1.0.2
    - future==0.17.1
    - hackingtools==0.9.912
    - httplib2==0.12.0
    - idna==2.8
    - isort==4.3.16
    - itsdangerous==1.1.0
    - jinja2==2.10
    - keyring==19.0.1
    - lazy-object-proxy==1.3.1
    - macholib==1.11
    - markupsafe==1.1.0
    - mccabe==0.6.1
    - msgpack-python==0.5.6
    - netaddr==0.7.19
    - netifaces==0.10.9
    - pefile==2018.8.8
    - pillow==2.9.0
    - pkginfo==1.5.0.1
    - pycparser==2.19
    - pygments==2.3.1
    - pyinstaller==3.4
    - pylint==2.3.1
    - pymetasploit==1.1
    - pypdf2
    - python-nmap==0.6.1
    - pytz==2018.9
    - readme-renderer==24.0
    - requests==2.21.0
    - requests-toolbelt==0.9.1
    - shodan==1.11.1
    - six==1.12.0
    - sqlparse==0.3.0
    - tqdm==4.31.1
    - twine==1.13.0
    - typed-ast==1.3.1
    - urllib3==1.24.1
    - webencodings==0.5.1
    - werkzeug==0.14.1
    - wrapt==1.11.1
    - xlsxwriter==1.1.5

