name: ht
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - openssl=1.1.1b
  - pip=19.0.3=py37_0
  - python=3.7.2
  - setuptools=40.8.0=py37_0
  - sqlite=3.27.2
  - wheel=0.33.1=py37_0
  - pip:
    - altgraph==0.16.1
    - astroid==2.2.5
    - beautifulsoup4==4.8.0
    - cffi==1.12.1
    - chardet==3.0.4
    - click==7.0
    - click-plugins==1.0.4
    - colorama==0.4.1
    - dis3==0.1.3
    - django
    - flask==1.0.2
    - future==0.17.1
    - hackingtools==0.9.939.45
    - html5lib==1.0.1
    - httplib2==0.12.0
    - idna==2.8
    - isort==4.3.16
    - itsdangerous==1.1.0
    - jinja2==2.10
    - lazy-object-proxy==1.3.1
    - macholib==1.11
    - markdown==3.1.1
    - markupsafe==1.1.0
    - mccabe==0.6.1
    - mechanize==0.4.2
    - msgpack
    - msgpack-python==0.5.6
    - netaddr==0.7.19
    - netifaces==0.10.9
    - pefile==2018.8.8
    - pillow==2.9.0
    - progressbar2==3.42.0
    - pycco==0.6.0
    - pycparser==2.19
    - pyinstaller==3.4
    - pylint==2.3.1
    - pymetasploit==1.1
    - pypdf2==1.26.0
    - pyreadline==2.1
    - pystache==0.5.4
    - python-nmap==0.6.1
    - python-utils==2.3.0
    - pytz==2018.9
    - rarfile==3.0
    - requests==2.21.0
    - shodan==1.11.1
    - smartypants==2.0.1
    - soupsieve==1.9.2
    - sqlparse==0.3.0
    - typed-ast==1.3.1
    - urllib3==1.24.1
    - werkzeug==0.14.1
    - wrapt
    - xlsxwriter==1.1.5

